name: hm3-automation CI

on:
  push:
    branches:
      - 'release/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Version
      shell: bash
      id: set-beta-manifest
      run: echo "::set-output name=version::$(node ./.github/workflows/beta-update-manifest.js ${{ github.ref }})"
    - name: install node v16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Foundry Type Install
      run: npm install --save-dev @league-of-foundry-developers/foundry-vtt-types@0.8.9-10
    - name: tsc
      run: tsc
    - name: Create module
      run: zip -r ./module.zip module.json LICENSE README.md lang/ templates/ scripts/ packs/ icons
    - name: Create Beta Release
      id: create_beta_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        name: Beta
        draft: false
        prerelease: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './module.json,./module.zip'
        tag: beta
